#! /bin/bash

BIN_DIR=$MYPORTS_DIR/bin

bin-help() {
cat << __EOM__
Usage: myports bin <command> ...

Commands:
  add <file>
          : register new script (with commit)
  commit  : commit changes
  list    : list entries
  path    : print path
  rm <entry-name>
          : remove registered script (with commit)
__EOM__
}

# Sub-commands
# ------------

bin-add() {
  cp $1 $BIN_DIR
  new_entry=$(basename $1)
  cd $MYPORTS_DIR
  git add bin/$new_entry
  git commit -m "Add ${new_entry}"
}

bin-commit() {
  cd $MYPORTS_DIR
  entries=$(git diff --name-only bin | cut -sd / -f 2- | tr '\n' ' ')
  git add bin
  git commit -m "Edit ${entries}"  
}

bin-list() {
  cd $BIN_DIR
  find . -type f | cut -sd / -f 2-
}

bin-path() {
  echo $BIN_DIR
}

bin-rm() {
  cd $MYPORTS_DIR
  git rm $BIN_DIR/$1
  git commit -m "Remove $1"
}

# Main Script
# -----------

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        bin-help
        ;;
    *)
        shift
        bin-${subcommand} $@
        if [ $? = 127 ]; then
          bin-help
        fi
        ;;
esac