#! /bin/bash

export MYPORTS_DIR=${MYPORTS_DIR:-$HOME/.myports}
export MYPORTS_EDITOR=${MYPORTS_EDITOR:-code}
export MYPORTS_SHELL=${MYPORTS_SHELL:-bash}

myports-help() {
cat << __EOM__
Management user personal dotfiles and scripts
Usage: myports <command> ...

Commands:
  bin <subcommand>
          : management scripts, see 'myports bin help'
  commit  : 
  dotfiles <subcommand>
          : management dotfiles, see 'myports dotfiles help'
  edit    : open myports directory by MYPORTS_EDTOR=${MYPORTS_EDITOR}
  sh      : enter myports shell by MYPORTS_SH=${MYPORTS_SHELL}
  pull    : pull updates to github
  push    : push updates to github
  show-remote
          : show remote information

Note:
  Add 'export PATH=\$(myports bin path):\$PATH' to your profile to use your commands.
__EOM__
}

# Sub-commands
# ------------

myports-commit() {
  cd $MYPORTS_DIR
  git commit -a -m 'myports commit'
}

myports-edit() {
  $MYPORTS_EDITOR $MYPORTS_DIR
}

myports-sh() {
  echo "Enter ${MYPORTS_DIR}"
  cd $MYPORTS_DIR
  $MYPORTS_SHELL
}

myports-pull() {
  cd $MYPORTS_DIR
  git pull
}

myports-push() {
  cd $MYPORTS_DIR
  git pull
}

myports-show-remote() {
  cd $MYPORTS_DIR
  git remote -v
  git diff origin/master
}

# Main Script
# -----------

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        myports-help
        ;;
    *)
        shift
        myports-${subcommand} $@
        if [ $? = 127 ]; then
          myports-help
        fi
        ;;
esac