#! /bin/bash

BIN_DIR=$MYPORTS_DIR/bin

bin-help() {
cat << __EOM__
Usage: myports bin <command> ...

Commands:
  install : make symlinks of all dotfiles to MYPORTS_USER_BIN(=${MYPORTS_USER_BIN})
  list    : list dotfiles
  path    : print path
  register <file>
          : register a script
  rm <script>
          : unregister a script
__EOM__
}

# Sub-commands
# ------------

bin-list() {
  cd $BIN_DIR
  find . -type f | cut -sd / -f 2-
}

bin-path() {
  echo $BIN_DIR
}

bin-register() {
  cp $1 $BIN_DIR
  new_entry=$(basename $1)
  cd $MYPORTS_DIR
  git add bin/$new_entry
  git commit -m "Add ${new_entry}"
}

bin-rm() {
  cd $MYPORTS_DIR
  git rm $BIN_DIR/$1
  git commit -m "Remove $1"
}

# Main Script
# -----------

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        bin-help
        ;;
    *)
        shift
        bin-${subcommand} $@
        if [ $? = 127 ]; then
          bin-help
        fi
        ;;
esac