#! /bin/bash

DOTFILES_DIR=$MYPORTS_DIR/dotfiles

dotfiles-help() {
cat << __EOM__
Usage: myports dotfiles <command> ...

Commands:
  diff    : diff between preserved and installed
  install : make symlinks of all dotfiles 
  list    : list dotfiles
__EOM__
}

# Sub-commands
# ------------

dotfiles-diff() {
  for f in $(dotfiles-list); do
    diff -u $DOTFILES_DIR/$f $HOME/$f
  done
}

dotfiles-install() {
  echo "Create symlinks..."
  for f in $(dotfiles-list); do
    echo "create $HOME/$f -> $DOTFILES_DIR/$f"
    ln -s $DOTFILES_DIR/$f $HOME/$f
  done
}

dotfiles-list() {
  cd $DOTFILES_DIR
  find . -type f | cut -sd / -f 2-
}

dotfiles-register() {
  cp -r $1 $DOTFILES_DIR
  new_entry=$(basename $1)
  cd $MYPORTS_DIR
  git add dotfiles/$new_entry
  git commit -m "Add ${new_entry}"
}

bin-rm() {
  cd $MYPORTS_DIR
  git rm dotfiles/$1
  git commit -m "Remove $1"
}

# Main Script
# -----------

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        dotfiles-help
        ;;
    *)
        shift
        dotfiles-${subcommand} $@
        if [ $? = 127 ]; then
          dotfiles-help
        fi
        ;;
esac